# Generated by Django 4.2 on 2023-05-04 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_auto_20230430_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Vacuna antiviral A', 'Vacuna antiviral A'), ('Vacuna antiviral B', 'Vacuna antiviral B'), ('Castración', 'Castración'), ('Vacuna Desparasitante', 'Vacuna Desparasitante'), ('Atención Clínica', 'Atención Clínica')], max_length=25, unique=True, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'tipo',
                'db_table': 'tipos_atencion',
            },
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('raza', models.CharField(max_length=100, verbose_name='Raza')),
                ('tamanio', models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=10, verbose_name='Tamanio')),
                ('fecha_nac', models.DateField(verbose_name='Nacimiento')),
                ('color', models.CharField(max_length=100, verbose_name='Color')),
                ('id_dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
            options={
                'verbose_name': 'perro',
                'db_table': 'perros',
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('observacion', models.TextField(null=True, verbose_name='Observacion')),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perros.perro')),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perros.tipo_atencion')),
            ],
            options={
                'verbose_name': 'atencione',
                'db_table': 'atenciones',
            },
        ),
    ]
