# Generated by Django 4.1.7 on 2023-05-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro',
            old_name='id_dueño',
            new_name='cliente',
        ),
    ]
