# Generated by Django 2.2.3 on 2023-04-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=12, verbose_name='Telefono'),
        ),
    ]
