# Generated by Django 2.2.3 on 2023-04-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20230430_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(max_length=8, unique=True, verbose_name='DNI'),
        ),
    ]
