# Generated by Django 2.2.3 on 2023-04-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20230430_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(unique=True, verbose_name='DNI'),
        ),
    ]
