# Generated by Django 4.1.7 on 2023-05-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_cliente_apellido_alter_cliente_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.PositiveIntegerField(verbose_name='Telefono'),
        ),
    ]
